### ISSUE TITLE
Bug when switching VPN server

### ISSUE THREAD

**Issue by chemicalbuz** [pyamsoft/tetherfi#190]
I've notice there's a bug when switching VPN server (I use surfshark app for Android): if I switch VPN server when tetherfi is running, the connection won't work any more and the only way to fix it is to restart the phone where tetherfi is installed. Although the connection works if I turn the VPN off. 
If I stop tetherfi, switch VPN server, and turn tetherfi on again works without issues.

**Comment by pyamsoft** [comment]
This is an issue caused by two things

Both TetherFi and the VPN generally expect to be "the only one" handling
network related stuff. If switching VPN servers with TetherFi on causes the
VPN connection to break, there is little I can do as I do not have the
ability to account for VPN connections. TetherFi just starts a Wi-Fi direct
network, which is completely independent of any VPN status.

You already seem to have figured out the work around, which is to make sure
TetherFi is off before attempting any VPN related configuration. There is
little I can do here, though this is good as documentation.

**Comment by chemicalbuz** [comment]
Sure that's not a big deal, you could add a warning to let users know to
turn tetherfi off before switching server to avoid issues. Keep up the good
work! Cheers

Il Dom 9 Lug 2023, 20:30 pyamsoft ***@***.***> ha scritto:
