### ISSUE TITLE
Random disconnections 

### ISSUE THREAD

**Issue by legolad81** [pyamsoft/tetherfi#202]
App is overall great when it works. I'm using it on a Samsung Note 9 to tether my Asus Chromebook.
I'll start the app, and usually put it on the charger as to not drain the battery down. The Chromebook will connect
The connection will sometimes hold other times the Chromebook will loose the connection. Seem to happen around the time the phone screen has turned off. As soon as I wake up the phone, the connection will return. I've gone over all settings and I cannot find any issues. Again, it's not consistent. Sometimes it will work without issue. Other times it will drop it over and over in a short span of time. My wife uses the app to connect her Pixel 6 to her MacBook and rarely has issues.  Any help is appreciated.

**Comment by pyamsoft** [comment]
Have you enabled the optional Wake locks from the hotspot configuration screen? Usually the spotty behavior with the screen off is caused by battery saving.

Make sure both wake lock switches are on, and you have Always Alive turned on as well

**Comment by legolad81** [comment]
I do have all those settings checked on and that's what baffles me. I
changed the settings recently to work on 2.4ghz just in case 5ghz was
unstable. No change. Not sure if of you know what else I might try.

My T-Mobile connection has been a little unstable so I wonder if it has
something to do with that? It doesn't seem to be disconnecting from the
wireless network but it's possible something is happening in the
background.

**Comment by pyamsoft** [comment]
It could be a network reliability thing

Since your phone is hosting the network as a proxy, data needs to hop through it too before getting to your Chromebook. If your network connection on the phone is spotty it could be resulting in issues on the laptop side, but noticing that it only happens when the screen is off sounds like your phone is going into some kind of power saving throttle mode which is outside of the apps control. 

I'd check your phone settings app for any system level power bits, Samsung usually has additional power tweaks that Google phones do not for example. As a third party app, I cannot touch these.

**Comment by legolad81** [comment]
Thanks for getting back to me. I'll look more into it and see if I can find
a pattern. Yesterday it worked flawlessly without a single drop in
connection. Regarding Samsung power settings, I did check those and I think
they are fine. Apps otherwise great!
