### ISSUE TITLE
TetherFi has failed to start

### ISSUE THREAD

**Issue by JJdastoner5099** [pyamsoft/tetherfi#223]
![Uploading Screenshot_20231009-095144.png…]()

TetherFi has been displaying this message regardless of what port number I use.

**Comment by pyamsoft** [comment]
Can you reupload the screenshot, looks like Github ate it

**Comment by JJdastoner5099** [comment]
![Screenshot_20231009-095144](https://github.com/pyamsoft/tetherfi/assets/146918796/b1150330-8596-42fc-af72-889fa1c7ba13)

**Comment by pyamsoft** [comment]
How odd, the app has never worked for you? Have you tried restarting the device?

Since TetherFi has no analytics or tracking, I dont actually know what the specific problem is yet.

I will create a new version which includes more error message information in the UI. That way we will be able to see what the exact error is that is causing your connection problem.

What about the other settings like network name and band?

**Comment by pyamsoft** [comment]
Recent changes to version 38 may have improved this situation. Can you check with 38 and see if this still occurs?

**Comment by pyamsoft** [comment]
Hello

Version 40 is recently released on the play store. Please download it when you have the chance and try enabling the "Stubborn Proxy" tweak. Thanks!
