### ISSUE TITLE
Ps5 dns settings 

### ISSUE THREAD

**Issue by Snappyj229** [pyamsoft/tetherfi#257]
Is there a way to manually change the dns settings in the ps5 to be able to have online access because right now the way its set up I can play online with friends or buy games just update games

**Comment by pyamsoft** [comment]
Hi!

Right now there is not sadly :(
We are only able to proxy "normal" Internet connections, but cannot do online gaming connections because of an Android OS limitation.

The PlayStation store is also very negative towards proxy networks like ours and seems to actively work against us at times sadly :(

**Comment by Snappyj229** [comment]
i figured but wanted to give it a shoot and i tried everything i found online to help like changing it manually to google dns 8.8.8.8 and 8.8.4.4 and couple other ones like 1.1.1.1 and 1.0.0.4 but nothing worked but if you guys on here find a way let me know or need help testing anything im here shoot me a email leeingram155@gmail.com

**Comment by pyamsoft** [comment]
Thanks! For the time being no amount of tweaking is going to help but as an owner of a PS4 this is always in the back of my mind for support. Happy Holidays!
