### ISSUE TITLE
cleartextTraffic

### ISSUE THREAD

**Issue by IzzySoft** [pyamsoft/tetherfi#263]
Sorry for bothering you, but I just need some clarification. The updater of my repo (which recently got some security checks added) just reported to me:

    ! repo/com.pyamsoft.tetherfi_40.apk declares flags: usesCleartextTraffic

I guess that's needed in your case, but before I add it to your app's allow-list with a reason I *think* stands behind it, can you please tell me the real one? Thanks in advance!

**Comment by pyamsoft** [comment]
Hi

Since TetherFi is a proxy we just forward the network requests of other applications. Many use clear text traffic for connectivity checking upon initially connecting to a wifi network, thus we need the flag.

TetherFi itself actually makes no internet connections except those that are fired as an implementation detail of using the Google version checker library

**Comment by IzzySoft** [comment]
Thanks for confirming! That was about what I thought it would be. Will add it to the allow-list for TetherFi then … done.
