### ISSUE TITLE
Hi link for kofi or similar :]

### ISSUE THREAD

**Issue by nonogamester** [pyamsoft/tetherfi#276]

**Comment by pyamsoft** [comment]
Hi! I appreciate the thought!

Sadly this won't happen, for the reason I outlined in #205. I'll paste it here below:


tl;dr: I've re-evaluated this and don't believe this will be coming - maybe ever.

What this essentially comes down to is: If I remove the tip-jar from the application, I would not be able to replace it with any kind of alternative. Google Store policy has been argued back and forth on the internet, but I take the safe paranoid approach to it: Any website your app links to or is hosted on cannot have alternative links for tips, it all must go through Google. So that means no Kofi, no Github Sponsors, no FDroid donations. If the app ever sees a cent, it has to pass through Google.

The billing code is easy enough to remove if someone wishes to fork the app into a fully-FOSS flavor. But it would be a fork and thus wouldn't be associated with me at all. And that's fine. Take the app, fork it, change the branding and the logo and stick it up on FDroid. But sadly its not something I will be pursuing at this time.

TetherFi, and all pyamsoft Android apps, will only ever be officially distributed and supported on the Google Play Store.
