### ISSUE TITLE
Transparent proxy

### ISSUE THREAD

**Issue by wspvlv** [pyamsoft/tetherfi#278]
Is it possible to set up a transparent proxy, so that one doesn't have to configure each app to use the proxy and to make programs that are oblivious to their existence to work through proxy?

**Comment by pyamsoft** [comment]
Hi, good question but sadly tl;dr no.

Nothing prevents you from setting up your own Proxy as the transparent between TetherFi and a client, but given that TetherFi is not a root app we cannot take over the networking stack like you would on a PC

As a result, all connections have to be explicit because its a fully userspace, unprivileged setup.

**Comment by wspvlv** [comment]
I don't see how that's an issue. The client need to be configured to send all its packets through the proxy server, not the server itself. So if the client OS is versetile enough it should work.

**Comment by pyamsoft** [comment]
Yes, thus nothing is preventing your client configuration from doing so, but its not the job of TetherFi, as it is the server in this case.

Whatever you are using to connect should be configured to send through the Proxy instead.

**Comment by brlin-tw** [comment]
> The client need to be configured to send all its packets through the proxy server, not the server itself.

The server still needs to configure firewall rules (as root) to masquerade the source IP address fields of these "packets" so that the response packets can reach back to the server and in turn to the client itself.

If you are certain this can be done without root privileges please elaborate on the _exact_ technical way to do it, otherwise, we can't implement it.
