### ISSUE TITLE
random, sudden disconnects

### ISSUE THREAD

**Issue by Plebian0789** [pyamsoft/tetherfi#321]
All wake locks are on, everything is optimized for maximum performance, I adjusted the power threads, and such, everything is on and in place o make sure i stay connected, but as soon as i turn off my broadcasting device, the receiving device gets no internet. The connection is still existent, just with no internet. It didn't happen when I used my data, just when I'm connecting to wifi only. I don't want to waste my data, or my battery power from keeping the phone screen on, can you help me?

**Comment by pyamsoft** [comment]
What kind of device do you have?

It sounds like your device may have a custom power saving profile which ignores all the standard Android stuff -_-


Maybe https://dontkillmyapp.com/ may provide some helpful advice? Otherwise, there is not much I can do - if your device doesn't like apps running with the screen off there is very little I can do about it :(
