### ISSUE TITLE
Bandwidth Limit not working

### ISSUE THREAD

**Issue by MohammedALShimmary** [pyamsoft/tetherfi#329]
First i would like to thank you for this great app.

The issue is when I'm using the Bandwidth Limit at 2 MB . the connected device doesn't seem to be affected, because when I'm using speed tests like Fast.com , the speed is not limited and I'm getting above 10MB/s ( my max Data speed ).

I'm very new at reporting issues , please let me know what else is needed from me to help you diagnose this issue.

**Comment by pyamsoft** [comment]
I will see about the inaccurate bandwidth limit. When not using the limit, do you also hit 10 on fast.com?

**Comment by MohammedALShimmary** [comment]
Either turning it on or off has no effect , 4G LTE internet always goes between 7 MB/s - 12 MB/s .. So if the function ever gets functioning : a 2 MB/s should be a very distinguishable/obvious change.

**Comment by MohammedALShimmary** [comment]
Regarding my other closed topic, it is actually a serious one as without internet access to the essential apps , the whole purpose of tethering is in vain.

BTW , enabling or disabling the bandwidth limiter has no effect on internet access to these apps : 

Telegram
WhatsApp
Facebook
Instagram
Threads
Speedtest by Ookla

**Comment by MohammedALShimmary** [comment]
Okay , Is ther any work around for making them work , If i use VPN connection by another app maybe ? 

Regarding the Bandwidth limiter , If you need any log or anything to help you diagnose it , let me know.

**Comment by pyamsoft** [comment]
I unfortunately do not know. I know other apps that perform a similar function to this one exist, like Net share for example. You are welcome to try those to see if they have managed to solve the problem somehow.

**Comment by pyamsoft** [comment]
Hello

Just an update, I have noticed that the bandwidth limit is incorrectly applied per-socket instead of per-client. As a result, it leads to wildly different numbers than expected. I have a new dev build in the works that I am testing with that gives much closer numbers on fast.com

A limit will never be perfect, but the old code was very far off and this is considerably closer. I hope to release this in the next version. Thank you for your patience. I will update again as release gets closer.
