### ISSUE TITLE
Can't Connect to Tailscale+Moonlight from TetherFi Hotspot Client

### ISSUE THREAD

**Issue by ataraxia-admail** [pyamsoft/tetherfi#342]
Firstly, its a great app. My issue involves using tetherFi for sharing uncapped 5g internet from phone to ipad. So, it works as intended, but Ipad can't connect to tailscale when using tetherFi hotspot shared from my phone. I saw from other posts that you said you also use it to connect it to your tailscale networks, i hope that you can help me with this issue.

**Comment by pyamsoft** [comment]
Hi

At least for my own setup, as long as my phone (the device running TetherFi) is connected to TailScale, then every device connected to my phone is also connected to the TailScale tunnel

Since the phone is a proxy, all devices using TetherFi will appear as though they "are" the phone. So you wouldn't connect your iPad to TailScale itself in this setup.

**Comment by pyamsoft** [comment]
Depending on how you use moonlight it might work - I use moonlight as an RDP basically here's how it works for me.


I only allow moonlight connections over TS, so I've got machine1 in moonlight at the direct IP of 100.200.3.4.

For my own setup, the phone is connected to the tailnet and is able to see machine1 by IP, and thus a proxied laptop is also able to see machine1 via direct IP.

If that is not working for you, not sure why sadly :(

**Comment by pyamsoft** [comment]
I assume your moonlight back end is using sunshine not the nvidia game stream? I have no idea if the official nvidia GS would work with this

**Comment by ataraxia-admail** [comment]
Yes i am using sunshine + moonlight setup. Are there any configurations you have done on your pc/tailscale/moonlight/sunshine?Mine was a pretty basic setup from tutorials.

I tried re-adding the host and found out that if doing so with TetherFi connected, my ipad's moonlight just couldn't pair with my pc, even with the correct paring pin, it would just say wrong pin while the request will times out. My phone is still able to remotely access my desktop even so there's that.

**Comment by pyamsoft** [comment]
Ah yeah the PIN wouldnt work over the proxy I dont think.

You should be able to first add the device normally off of TetherFi, and then once you are authorized, connect to TetherFi, and manually add the device by IP address in moonlight, which will keep the PIN active and will just "override" the known IP address.

I hope that makes sense, but this what had worked for me

**Comment by pyamsoft** [comment]
I assume the PIN step in moonlight doesn't use normal HTTP communication, so TetherFi is unable to "speak it", which is why it doesn't work

**Comment by ataraxia-admail** [comment]
> I hope that makes sense, but this what had worked for me
Makes sense, sadly thats exactly what hadn't worked for me
Moonlight just doesnt work if i use tetherFi unless i am missing out some configurations

**Comment by ataraxia-admail** [comment]
>  and manually add the device by IP address in moonlight, which will keep the PIN active and will just "override" the known IP address.

Wait what do you mean by that, do i add the PC's IP(tailscale ip) in moonlight 2nd time even after connecting to tetherFi or i just do it beforehand as mentioned and it should theoretically just be able to access it which didn't work for me?

**Comment by pyamsoft** [comment]
Those steps you've outlined above are the exact ones that work for me :(

Unfortunately I don't know enough about how TS and moonlight and sunshine function internally to be of further help here, sorry :(

**Comment by pyamsoft** [comment]
One important difference for our setups is that I am connecting 2 PCs, while you are connecting and iPad and a PC

Maybe something about specially the iPad mobile app is a limiting factor

Sorry that I can't be more help

**Comment by pyamsoft** [comment]
Hi

After some rerunning of tests and various reading into sunshine and moonlight I need to apologize

Due to the fact that right now we are only an HTTP proxy, moonlight will not work over a proxy connection like TetherFi. I was misremembering information from a previous test build.

TailScale does work for anything that is a "normal" http - but as sunshine heavily uses UDP it will NOT work.

Sorry again for the confusion - at the moment sunshine/moonlight is not able to be supported.

**Comment by ataraxia-admail** [comment]
> at the moment sunshine/moonlight is not able to be supported.

Ah, understand. The question would be, would this ever be supported in the future, or at least is it technically feasible to implement this feature? 

Afterall, having a non-cellular ipad with capped network speeds on moonlight is a bummer when it has potential to support full resolution streams

**Comment by pyamsoft** [comment]
Possibly it could work in the far future if I am able to implement a UDP associating SOCKS proxy but I wouldn't bet on it - Moonlight project has stated before that usage over proxy is generally unsupported due to the heavy bandwidth requirements of streaming.

At this point our limitations are technical, but I won't say "never", just rather we may need to be patient :)

**Comment by ataraxia-admail** [comment]
Would love to see it if it comes 👍
