### ISSUE TITLE
Incompatible with Graphene OS sandboxing

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [pyamsoft/tetherfi#357]
There is no way to use it with[ other vpn apps](https://f-droid.org/packages/se.leap.riseupvpn/)

https://play.google.com/store/apps/details?id=com.gorillasoftware.everyproxy
> It can be used with any VPN and sends VPN traffic to the LAN so that the PC can also use VPN traffic from the phone device.

Request Tetherfi to support this implementation

**Comment by pyamsoft** [comment]
Hi

Let's say you are running TetherFi on your device, D

Where are you running the VPN app? Also on device D, or on another device?

Thanks

**Comment by pyamsoft** [comment]
Hi

For this use case, the VPN itself would need to support a local network sharing option. It appears the RiseUp application you linked me sadly does not yet.

Other tools like every proxy work because they rely on the device hotspot and go over an existing network interface. TetherFi uses WiFi direct and creates its own interface, and this technical change is what allows one to work and one to not.

If RiseUp implemented a local network sharing ability, TetherFi would work with it. However, given the stated goal of the project it doesn't seem like this are open to doing this.

I recommend for the time being you stick with your existing setup of every proxy if you are looking to use RiseUp as your VPN service.

**Comment by pyamsoft** [comment]
Hello

I just downloaded the RiseUp VPN and was able to connect to TetherFi while it was running.

An IP check confirmed that the RiseUp VPN was getting sent over TetherFi, so the apps are compatible on my device at least.

In the TetherFi settings, make sure you have the "Ignore VPN" toggle switched on. Start RiseUp before you start TetherFi, and try again.

**Comment by pyamsoft** [comment]
Not possible at the moment, no. Unfortunately I am not able to support custom ROM features like the ones Graphene provides.

If there is a way to run it "non sandboxed" would that fix the issue?

**Comment by pyamsoft** [comment]
I see, then in that case as I said before there is nothing I can do. RiseUp VPN works on my device using a manufacturer ROM, and I don't have the bandwidth to support custom builds like Graphene right now, sorry
