### ISSUE TITLE
Custom ssid without preface and network for iot device recovery

### ISSUE THREAD

**Issue by dkebler** [pyamsoft/tetherfi#359]
I'm looking for a tool that I can use to gain recovery access to an iot device, in my use case that's a tasmota on ESP 32 that uses Wi-Fi to get on a network.  If the device can't reach that set access point then I'm fubard and I have to take the device and connect it to a computer and reflash it. It would be WAY easier to use my phone as a recovery access point and just get near to the device. Then I can power cycle it and talk to its web interface directly from my phone since the set WAP is unavailable  e.g.  its SSID and or password got changed.

So my questions are

1. It looks like your SSID setting  has a permanent preface on it. Can I remove that so I can have my own custom SSID without that preface.?.    

2.   Can I specify a specific subnet for my phone and whatever device attaches to it. For example 192.168. 20. 0 / 30 ?.  I  will not need access to my cell carrier nor the local lan during this just need a mini Network between my phone and the device. I will need to run a DHCP server on my phone too because the iot device doesn't have a static IP.  That might be a good feature to add to tetherfi?

Just so you know the iot device does have AP mode but I deliberately disable that because if the thing gets reset too much it like flickering power outages it goes into AP mode as a recovery on its own when it doesn't find the AP it was programmed for. That can happen after a power outage when everything boots up out of sequence. Like the ESP long before the set access point. 

Sorry to fill up your issue tracker with questions but you're not running a discussion on this repo, recommended, so this is the only way it seems I can contact you.   thanks!

**Comment by pyamsoft** [comment]
Hi, thanks for the questions.

1. No, sadly, since we use WiFi direct, the prefix DIRECT-blah is enforced

2. Also as a side effect of WiFi direct, and the fact that during this setup we don't control the DNS, DHCP, route table, ARP cache, or anything, no you cannot edit the subnet either.

Sad TLDR is: no and no, and its out of our control :(

Maybe one day I could support spinning up just a generic DHCP server, but its honestly so far our of scope right now I've given zero thought to it.


You may be able to have some kind of Frankensteined setup using TailScale, but thats not really my place to say what your setup looks like.
