### ISSUE TITLE
Unable to compile > Could not find io.ktor:ktor-network:3.0.1-PYAMSOFT

### ISSUE THREAD

**Issue by maxbrito500** [pyamsoft/tetherfi#367]
This was a fresh clone of the project [1] today at an empty folder, running the most recent android studio (ladybug 2024.2.1 Patch 3).

Below is the error message when trying to compile.

How can this be solved?

Thank you in advance.

```
94: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':ui:mergeDebugAndroidTestNativeLibs'.
> Could not resolve all files for configuration ':ui:debugAndroidTestRuntimeClasspath'.
   > Could not find io.ktor:ktor-network:3.0.1-PYAMSOFT.
     Required by:
         project :ui > project :server

* Try:
```

[1] commit version: https://github.com/pyamsoft/tetherfi/commit/33f28f2d4d5faead27ce0db425ab61cd867d0ec8

**Comment by bldg-peter** [comment]
Hi, please see #348, which talks about the same problem.

This project uses a fork of Ktor, which you will need to build yourself.

**Comment by pyamsoft** [comment]
Hi, please see #348

This project uses a fork of ktor, which you will need to build yourself

**Comment by maxbrito500** [comment]
Hello, please don't close the ticket so quickly.

Anyone trying to compile the source code will stumble on the same issue. Was now looking in the archive and this has been mentioned before. 

Just "build yourself tor" isn't helpful, the complete instrutions can be found here: https://github.com/pyamsoft/tetherfi/issues/348#issuecomment-2460456067

Can you please include a section "How to compile" so that this error does not reoccur for others?

If you want, I can also submit that section as documentation but might be more pratical for you to write it.

Thank you.

**Comment by pyamsoft** [comment]
Hi sorry about that

The issue is pinned and has instruction included in it, so I figure that anyone looking for a build solution would see the pinned issue first as a due diligence.

I will look to add a section to the wiki about compilation, but the fork is a temporary solution until upstream supports a single line of code addition. At the point ktor can complete my feature request, the fork will no longer be needed and the project would build out of the box.
