### ISSUE TITLE
Considered Unstable

### ISSUE THREAD

**Issue by Drago-Cuven** [pyamsoft/tetherfi#373]
This is an issue I found with discord but could possibly be a problem elsewhere.

 I'm on ChromeOS
![image](https://github.com/user-attachments/assets/f60526d2-c9a6-4f0e-aa13-ab1706d37bc3)

I can't get into any discord call whatsoever whether its in dms or a server voice chat or stage.
it always tries to connect, then gets stuck on "checking route", flickers to "no route", then rinse and repeat.
![image](https://github.com/user-attachments/assets/d5d94061-305b-4322-885d-352b54ee6158)

**Comment by pyamsoft** [comment]
Hi, Happy Holidays

This is the same issue as the long standing issue that the app currently does not have support UDP, so things like Discord won't work properly.

You may have more success using Discord via its website version, as this only communicates over TCP and may be better - though I haven't testes myself yet.

I know this is a problem and unfortunately unless discord provides settings in its own app to support proxies, there is not much we can do here sadly :(

**Comment by Drago-Cuven** [comment]
i AM using the website version. thats why i'm so confused.

**Comment by pyamsoft** [comment]
Oh weird, well then I guess Discord just doesn't like us :(

Unfortunately, since the proxy is "just a proxy" there isn't much I can do to get specific services working. They basically either "work or don't"

I will add Discord on Chrome OS to the list of known apps that don't work. Sorry to see voice isn't functioning over the service.
