### ISSUE TITLE
Feature suggestion: Include a Quick Settings tile so users can start/stop tethering with a tap

### ISSUE THREAD

**Issue by e-t-l** [pyamsoft/tetherfi#89]
It would be great for users to be able to add a tile for Tetherfi to their Quick Settings in the notification shade, so that tethering could be activated and deactivated without having to launch the app. Android makes it very straightforward for developers to create quick settings tiles using `tileservice`* I imagine you could even have the the text of the tile, when active, display whatever SSID and proxy port has been set.

*https://developer.android.com/develop/ui/views/quicksettings-tiles

**Comment by pyamsoft** [comment]
This could certainly be neat, I will look at it thanks.

Given the minApi is 23, and TileService is 24, I would probably bump the minSdk up to 24 if this were implemented.

There would also need to be a way to handle cases where the tether network fails because of Wifi Direct issues, since Wifi direct is lame.

Ill keep it top of mind moving forward and see what I can do when I next have time. 

Thank you!

**Comment by pyamsoft** [comment]
A simple TileService will be included in release 9.

I've noticed a few small bugs with behavior - generally when the app has not been opened in a long time. Attempting to toggle the tile will lead to an error that seems to be randomly resolved when you open the app and then try again.

I will continue to investigate, it feels like it may have something to do with the service being a bound service tied to the UI as opposed to a system operated tile.

**Comment by pyamsoft** [comment]
The tile service has been made more reliable by launching a transparent screen.

This feature is now basically implemented, but I will continue polishing the UI
